version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=https://your-firebase-database.firebaseio.com
    depends_on:
      - firebase
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  firebase:
    image: google/cloud-sdk
    command: tail -f /dev/null
    volumes:
      - ./backend/firebase-credentials.json:/app/firebase-credentials.json
